default_language_version:
  python: python
repos:
  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: pretty-format-json
        args: ['--autofix', '--indent 2', ]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell

  # API
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ["--config", "./api/pyproject.toml", . ]
        pass_filenames: false
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.265
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
      - id: python-safety-dependencies-check
        entry: safety
        args: [check]
        files: ./api/requirements-build.txt
# TODO: Run this hook from docker container.
#  - repo: local
#    hooks:
#      - id: migrations-check
#        language: system
#        name: Check for uncreated migrations.
#        entry: sh -c "make api-check-migrations"
#        files: models/*.*\.py$
#        stages: [commit]
